### ISSUE TITLE
Linking a Passkey to an existing model

### ISSUE THREAD

**Issue by Aupajo** [alliedcode/passkeys-rails#5]
Hi. I have a situation where my `User` record already exists, and I want to add a Passkey to it. It looks like the model with this library is that you can optionally create a record at registration, but there doesn't appear to be a mechanism to link a Passkey to an existing record. Is that right, or is there a workaround I could use?

**Comment by troya2** [comment]
Great question.  In your case, assuming there is a way for your users to authenticate currently, consider adding a Credential class, which would integrate with this gem by including `PasskeysRails::Authenticatable`.  Your User class would use `has_many :credentials`, and you could connect the credential to the user after the passkey registration step in the `registering_with` method of the `PasskeysRails::Authenticatable`.

In the Security section of our users existing Profile (or wherever makes sense in your case), allow them to "Add a passkey".  Use that to trigger the passkey registration process.

Let me know if this works for your use case, and if so, please consider updating the README to help others through the same process.

**Comment by Aupajo** [comment]
Thanks for the advice! I've decided to put this on hold for now for a few reasons, but hope this comment helps others.
